### ISSUE TITLE
findbugs-maven-plugin does not build with JDK 9-EA

### ISSUE THREAD

**Issue by simontunnat** [mojohaus/findbugs-maven-plugin#1]
When I try to build the plugin using the JDK 9 Early Access Version i get the following error:
`[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean (default) on project findbugs-maven-plugin: Execution default of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean failed: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/java-9-jdk/../lib/tools.jar -> [Help 1]`

Probably related to https://github.com/mojohaus/cobertura-maven-plugin/issues/30

**Comment by hazendaz** [comment]
use [spotbugs-maven-plugin](https://github.com/spotbugs/spotbugs-maven-plugin)
