### ISSUE TITLE
The findbugs-maven-plugin and its dependencies must not be added to the auxClasspath

### ISSUE THREAD

**Issue by sewe** [mojohaus/findbugs-maven-plugin#2]
FindBugs distinguishes between the JARs/directories to analyze and the *auxiliary classpath*, as specified by the `-auxClasspath*` set of [command-line options](http://findbugs.sourceforge.net/manual/running.html). According to the documentation

> [The auxiliary classpath] should include all jar files and directories containing classes that are part of the program being analyzed but you do not want to have analyzed for bugs.

Unfortunately, the `findbugs-maven-plugin` (tested in version 3.0.3) does put *itself* and all *its transitive dependencies* on the auxiliary classpath. This is logically wrong and can, in some circumstances, slow things down: If a findbugs detector needs to calculate some information, e.g., a class hierarchy, based on the application’s entire classpath (application + auxiliary classpath), then it wastes a lot of time looking at `findbugs-maven-plugin-3.0.3.jar`, `findbugs-3.0.1.jar`, etc.

To demonstrate:

    mvn archetype:generate -DgroupId=org.apache.maven.archetypes -DartifactId=maven-archetype-quickstart -Dpackage=org.example -DinteractiveMode=false
    cd maven-archetype-quickstart
    mvn package org.codehaus.mojo:findbugs-maven-plugin:3.0.3:check -X | grep -i auxclasspath

The entire classpath passed to FindBugs can also be viewed in the `target/findbugsXml.xml` file, which contains a lot of `<AuxClasspathEntry>`s.

**Comment by sewe** [comment]
@mojohaus, @gleclaire: Just noticed that this repository is forked from gleclaire/findbugs-maven-plugin, but the [plugin’s website at Mojohaus.org](http://www.mojohaus.org/findbugs-maven-plugin/issue-tracking.html) lists this repository as the official issue tracker. Is this correct? Or should I report my issues against the upstream repository?

**Comment by gleclaire** [comment]
The official site is still https://github.com/gleclaire/findbugs-maven-plugin
Please put issue over there

**Comment by olamy** [comment]
@gleclaire so we should remove this mojo from here (mojohaus org)?

**Comment by gleclaire** [comment]
the next release will be from the current repository.  After that I can move it over.

**Comment by sewe** [comment]
> the next release will be from the current repository. After that I can move it over.

Having the plugin ultimately under `mojohaus/findbugs-maven-plugin` sounds good to me, as the MojoHaus website is IMHO second go-to place for Maven plugins, after [maven.apache.org](https://maven.apache.org/plugins/) itself.
